# Generated by Django 3.2 on 2022-05-01 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followship', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='requested',
            field=models.ManyToManyField(related_name='requested_by', through='followship.FollowRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
