# Generated by Django 3.2 on 2022-05-02 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followship', '0002_auto_20220502_0500'),
        ('accounts', '0002_myuser_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='requested',
        ),
        migrations.AddField(
            model_name='myuser',
            name='followings',
            field=models.ManyToManyField(related_name='followers', through='followship.FollowRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
