# Generated by Django 3.2 on 2022-05-01 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prof.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('bio', models.CharField(max_length=2047, null=True)),
                ('privacy', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PU', max_length=5)),
                ('image', models.ImageField(null=True, upload_to=prof.models.prof_image_dest)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
